FROM php:fpm-alpine as base
FROM base as builder

MAINTAINER Fisher Pri Catz "fisher.wei@wqfw.de"

RUN apk add --no-cache autoconf gcc linux-headers libc-dev make && \
        pecl install redis && docker-php-ext-enable redis
RUN apk add --no-cache libpng libpng-dev libzip-dev && \
        docker-php-ext-install pdo pdo_mysql gd zip \
        && apk del libpng-dev

