FROM python:3.6-alpine as base

FROM base as builder

MAINTAINER Fisher Pri Catz "fisher.wei@wqfw.de"

RUN apk update && apk upgrade && \
    apk add --no-cache bash git

WORKDIR /app

ENTRYPOINT ["bash", "-c", "git clone $GIT_REPO /app && pip install -r requirements.txt ; $ENTRYPOINT"]

